### ISSUE TITLE
[docs] Employee - Sequence Diagram, Class Diagram

### ISSUE THREAD

**Issue by Jummi10** [cau-swe/checkpoint-2#1]
### 선택한 Requirements
- 종업원은 로그인하여 주문 관리 페이지에 접속할 수 있다.
- 종업원은 주문 내역 을 확인할 수 있어야 한다.
- 종업원은 주문 상태 를 바꿀 수 있다.

### To do
- [x] Sequence Diagram
  - [x] UC-1 AuthenticateEmployee
  - [x] UC-7(UC-4 FindOrderDetail + UC-5 FindAdditionalOrderLine)
  - [x] UC-6 ChangeOrderState
- [x] Class Diagram

**Comment by kouz95** [comment]
resolve #1
